app.post("/signup", (req, res) => {
    db.users.find({
        "username": req.body.username
    }, async (err, result) => {
        if(err){
            return res.status(500).json({msg: "error"})
        } else if(result.length===0) {
            await db.users.insert(req.body)
            return res.status(200)
        } else {
            return res.status(409)
        }
    })
})

// ** passing an object to `db.insert()` fixes the vuln

app.post("/signup", (req, res) => {
    db.users.find({
        "username": req.body.username
    }, async (err, result) => {
        if(err){
            return res.status(500).json({msg: "error"})
        } else if(result.length===0) {
            await db.users.insert({
                username: String(req.body.username),
                password: String(req.body.password), //assuming password is already encrypted
                email: String(req.body.email),
                // isAdmin will be set internally
            })
            return res.status(200)
        } else {
            return res.status(409)
        }
    })
})